### ISSUE TITLE
Review: Athletics

### ISSUE THREAD

**Issue by jsprey** [Ixsen/Mastery#24]
Causes: 
* Bonus walking speed
* Bonus running speed
* Higher jumps
* Bonus swimming speed

Longer underwater time:
* scrapped for now, instead should take less damage through drowning in survival

**Comment by jsprey** [comment]
Bonus walking/running/swimming speed are working great. 

Higher jumps are currently quite useless because at level 500 you cannot even jump 2 blocks high. Actually, I do not see any difference. Is it not working?

All stats are only applied on level up. Upon spawning, they are not applied. I think it can be solved the same way as #20.

**Comment by Ixsen** [comment]
Jumping bonus is working, but the multiplier is currently set to 1. During balancing we can change the mutiplier as we want
