### ISSUE TITLE
We need to prevent benefits for the mining mastery of self placed block

### ISSUE THREAD

**Issue by jsprey** [Ixsen/Mastery#26]
The effects coming with mining allows a player to duplicate blocks like iron and gold blocks. Because they need to grant EXP and we should introduce a double drop, otherwise very inconsistent to diamonds/coal.

A double drop for iron and gold blocks is not possible because they can place them down again. And the story begins again...

**Comment by Ixsen** [comment]
Double chance will not apply for iron and gold anymore. Instead there will be skills that increase chance after smelting the ore
